version: '3.8'
services:
  bot:
    build: .
    volumes:
      - 'database:/app/db'
  dev:
    build: .
    volumes:
      - 'database:/app/db'
      - '.:/app'

volumes:
  database:
    external: false
